# Generated by Django 5.1.3 on 2024-11-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyauthenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='is_installed',
            field=models.BooleanField(default=True),
        ),
    ]
