# Generated by Django 5.1.3 on 2024-11-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyauthenticate', '0002_shopifystore_is_installed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
