# Generated by Django 5.1.3 on 2024-11-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyauthenticate', '0006_shopifystore_current_hmac'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='calculated_hmac',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
