# Generated by Django 5.1.3 on 2024-11-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyauthenticate', '0007_shopifystore_calculated_hmac'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='canAsk',
            field=models.BooleanField(default=False),
        ),
    ]
