# Generated by Django 5.1.3 on 2024-11-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyauthenticate', '0008_shopifystore_canask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifystore',
            name='is_installed',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
