# Generated by Django 5.1.3 on 2024-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyauthenticate', '0009_alter_shopifystore_is_installed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopifystore',
            name='canAsk',
        ),
        migrations.AddField(
            model_name='shopifystore',
            name='urlsPassed',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
