# Generated by Django 5.1.3 on 2024-11-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyauthenticate', '0010_remove_shopifystore_canask_shopifystore_urlspassed'),
        ('shopifyauthenticate', '0013_alter_shopifystore_urlspassed'),
    ]

    operations = [
    ]
