# Generated by Django 5.1.3 on 2024-11-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyauthenticate', '0014_merge_20241123_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystore',
            name='shop_id_from_shopify',
            field=models.IntegerField(default=0),
        ),
    ]
