# Generated by Django 5.1.3 on 2024-11-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='product_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
