# Generated by Django 5.1.3 on 2024-11-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_useractivity_product_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelationship',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('related_product_ids', models.JSONField()),
            ],
        ),
    ]
