# Generated by Django 5.1.3 on 2024-11-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_productrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
