# Generated by Django 5.1.3 on 2024-11-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_productrecommendation_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='customer_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
