# Generated by Django 5.1.3 on 2024-12-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_productrecommendation_loggedin_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=255)),
                ('slider_styles', models.JSONField()),
                ('button_styles', models.JSONField()),
                ('close_button_styles', models.JSONField()),
                ('slide_styles', models.JSONField()),
            ],
        ),
    ]
