# Generated by Django 5.1.3 on 2024-12-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0009_slidersettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidersettings',
            old_name='button_styles',
            new_name='settings',
        ),
        migrations.RemoveField(
            model_name='slidersettings',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='slidersettings',
            name='close_button_styles',
        ),
        migrations.RemoveField(
            model_name='slidersettings',
            name='slide_styles',
        ),
        migrations.RemoveField(
            model_name='slidersettings',
            name='slider_styles',
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='customer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
