# Generated by Django 5.1.3 on 2024-12-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0010_rename_button_styles_slidersettings_settings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components_json', models.JSONField()),
            ],
        ),
    ]
