# Generated by Django 5.1.3 on 2024-12-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0011_dynamiccomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccomponent',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
