# Generated by Django 5.1.3 on 2024-12-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0012_dynamiccomponent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidersettings',
            name='renderedhtml',
            field=models.TextField(default=''),
        ),
    ]
