# Generated by Django 5.1.3 on 2024-12-10 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0013_slidersettings_renderedhtml'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOftenBoughtTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(help_text='Unique identifier for the customer.', max_length=20)),
                ('product_id', models.CharField(help_text='Unique identifier for the main product.', max_length=20)),
                ('recommended_products', models.JSONField(help_text='List of product IDs often bought together.')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the last update.')),
                ('notes', models.TextField(blank=True, help_text='Additional information or comments.', null=True)),
            ],
            options={
                'verbose_name': 'Often Bought Together Recommendation',
                'verbose_name_plural': 'Often Bought Together Recommendations',
                'ordering': ['-updated_at'],
                'unique_together': {('customer_id', 'product_id')},
            },
        ),
    ]
