# Generated by Django 5.1.3 on 2024-12-14 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0014_productoftenboughttogether'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255, unique=True)),
                ('shop', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Active User',
                'verbose_name_plural': 'Active Users',
                'indexes': [models.Index(fields=['shop', 'is_active'], name='recommendat_shop_a3dbd2_idx')],
            },
        ),
    ]
